spring:
  config:
    import:
      - 'classpath:adapter-http-property.yml'
      - 'classpath:adapter-persistence-property.yml'
      - 'classpath:adapter-redis-property.yml'
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3e25c34a33f5e543369404e512a02fcb
            client-secret: 3OigSvNqWeJZSM0zAJahCZzBeBvEZ5GH
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:3000/login/oauth2/code/kakao"
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret: fb900242fd4df1cfaf1f8cee116d142034581c75ed450798e16dffdc8e1f9128 # openssl rand -hex 32
  expire:
    access-token: 1
    refresh-token: 24